### PR TITLE
Add support for eslint 8, make eslint a peer dependency, and upgrade deps

### PR DESCRIPTION
**Pull request by davidmyersdev**
This script currently fails when running in a repo that uses `eslint` v8.

### CODE REVIEW

**Review by Austio — APPROVED** [review]

**Comment by LandonSchropp** [comment]
Any chance that this could get merged soon? I'd love to be able to use this project.

**Comment by LandonSchropp** [comment]
CC @markbrouch

**Comment by LandonSchropp** [comment]
I tested this on a repo with ESLint 8 and it works great!

**Comment by voracious** [comment]
Hey @LandonSchropp. Thanks for testing this out and letting us know! I also tested this internally, and we are safe to merge it in. I'll follow up with the team tomorrow to see when we can get a new release out.

**Comment by LandonSchropp** [comment]
Thank you!

**Comment by davidmyersdev** [comment]
@LandonSchropp this has been released as [`v0.2.0`](https://github.com/doximity/eslint-generate-todo/releases/tag/v0.2.0).

**Pull request merged**
